name: stunde
description: "A new Flutter project."

publish_to: "none"

version: 0.3.0+5

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  elbe: ^0.1.42
  macos_ui: ^2.0.9
  moewe: ^0.2.7
  system_tray: ^2.0.3
  hive: ^2.2.3
  file_saver: ^0.2.14
  flutter_file_saver: ^0.6.2
  file_picker: ^8.1.3
  hive_flutter: ^1.1.0

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/task/
    - assets/icons/aspect/

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "assets/app_icon.png"
